GTJ-60, GTJ-61
artem-loban/gitbook-test pull request #53
Opened 2021-05-26 11:20 UTC by FelixMemoStill

asdasd

2021-05-26 11:26 UTC, artem-loban commented
asdasd

2021-05-26 11:38 UTC, FelixMemoStill reviewed
qdasdasdasdacsc

2021-05-26 11:45 UTC, artem-loban requested changes
fgdfgd

2021-05-26 11:46 UTC, artem-loban approved these changes

2021-05-26 11:53 UTC, artem-loban requested changes
asdasdsdcasdcasc

2021-05-27 07:32 UTC, artem-loban commented
xfgdf

2021-05-27 16:08 UTC, closed without merging